### ISSUE TITLE
Crash on latest 1.10.2 version (2.5.11)

### ISSUE THREAD

**Issue by Dune-Jumper** [cubex2/chesttransporter#1]
When I click on the Tools tab in Creative mode the game crashes entirely. I went back to 2.5.10 and it works fine. Crash report: https://pastebin.com/awE0gXub

**Comment by Imnuts7** [comment]
Crashed on 1.11.2 as well while trying to look up recipe in JEI.

**Comment by cubex2** [comment]
Is fixed for 1.10.2 and 1.11.2 now.
