### ISSUE TITLE
Chest transporter and anti griefing

### ISSUE THREAD

**Issue by Raycoms** [cubex2/chesttransporter#10]
Hey there, would it be possible to call the "pickup" or "block break" events or similar when picking up chests?
Currently, all players on our server are able to grief others with the chest transporter mod because no events are called at all.
So it would be very important to clean that up.
Else we would have to remove that mod from the server.

**Comment by cubex2** [comment]
The "block break" event is now fired when picking up chests.

**Comment by Raycoms** [comment]
Have you updated it already on curse?

2017-05-06 6:53 GMT-03:00 cubex2 <notifications@github.com>:

**Comment by cubex2** [comment]
Yes, it's already on curse.

**Comment by Raycoms** [comment]
Thanks a lot =)

2017-05-06 10:38 GMT-03:00 cubex2 <notifications@github.com>:
