### ISSUE TITLE
Invisible Quark Chests [1.11]

### ISSUE THREAD

**Issue by Kisutora** [cubex2/chesttransporter#13]
Whenever I pick up a Quark chest, it doesn't show it on the item texture.
![quark_chest](https://user-images.githubusercontent.com/22685232/28485064-69c898d6-6e7f-11e7-9822-4fb5d9f5995a.png)
This problem is only with Quark chests, Vanilla and Storage Drawers work just fine.
![vanilla_chest](https://user-images.githubusercontent.com/22685232/28485097-a5226844-6e7f-11e7-908a-1c920d4f8d82.png)
I'm using Quark-r1.2-93 (latest version for 1.11) and ChestTransporter-1.11.2-2.7.9
with 1.11.2-forge1.11.2-13.20.1.2421

**Comment by Kisutora** [comment]
P.S. It would be really nice to get support for Storage Drawers Extras (https://minecraft.curseforge.com/projects/storage-drawers-extras?gameCategorySlug=mc-mods&projectID=254879) and maybe even Tinkers' Construct (https://minecraft.curseforge.com/projects/tinkers-construct?gameCategorySlug=mc-mods&projectID=74072) Pattern/Part Chests! Thanks! ;>

**Comment by cubex2** [comment]
The bug has been fixed and Storage Drawers Extras is supported again (it already was in 1.10.2). Please open a new issue for the Tinkers' Construct support.
