### ISSUE TITLE
Transporter picks up and immediately re-places chest

### ISSUE THREAD

**Issue by dimensionsintime** [cubex2/chesttransporter#14]
Using Forge 14.21.1.2419, Chest Transporter 1.12-2.8.5.  Chest is picked up and then immediately re-placed. Tried wood and iron transporter, on Iron Chests and Vanilla, same result.

**Comment by cubex2** [comment]
Fixed

**Comment by drakray** [comment]
CT 1.11.2-2.7.11 with Forge 1.11.2-2429 have the same problem
