### ISSUE TITLE
Request for Tinkers' Construct Support

### ISSUE THREAD

**Issue by Kisutora** [cubex2/chesttransporter#15]
Tinkers' Construct has 2 chests (part and pattern) that would make sense to be picked up by chest transporters. Any chance of adding support for these two chests? Thanks! :>
![tinkers_transporter](https://user-images.githubusercontent.com/22685232/28505825-a9b8f89e-702f-11e7-8475-d6893a9910e0.png)
I currently play on Minecraft 1.11.2.

**Comment by cubex2** [comment]
Added support for them in 1.10.2, 1.11.2 and 1.12
