### ISSUE TITLE
Modpack rule violates your own project license

### ISSUE THREAD

**Issue by C0rn3j** [cubex2/chesttransporter#19]
Hiya, you've licensed this mod as GPLv3 (awesome!).

You have this sentence on the CF project page

    You are allowed to include the mod in a modpack if you give visible credit to me (CubeX2).

which is in conflict with the license. Anyone can take the code and rerelease it however they want, as long as people executing the binary receive the source code.

My suggestion is to just change the sentence to "You can use it in any modpack you want".

**Comment by cubex2** [comment]
Good point. Changed it.
