### ISSUE TITLE
modid should be lowercase

### ISSUE THREAD

**Issue by Seegras** [cubex2/chesttransporter#4]
The modid ChestTransporter is not the
same as it's lowercase version. Lowercasing is enforced in 1.11

After fixing 
public static final String ID = "chesttransporter";
in ChestTransporter.java and 
  "modid": "chesttransporter",
in mcmod.info it works.

**Comment by cubex2** [comment]
The modid is already all lowercase in 1.11, fixed it in the mcmod.info file now.
As for 1.10.2, I'll leave the id as it is. Changing it now may cause problems with existing worlds. The game works perfectly fine so need to change it.
