### ISSUE TITLE
Effect bug

### ISSUE THREAD

**Issue by TheoTechnicguy** [cubex2/chesttransporter#5]
Hello,

I encountered 2 problems with the mod. I use the 1.10.2 version 2.5.14. First, with Quark, the dark oak chest looses the texture when placed down and, second, I keep the effects after I place the chest down.

If you need more info, feel free to contact me; I never know what I need to include...

Thanks.

**Comment by Protheus** [comment]
The wooden transporter is not used up, you see the animation but I still keep it.

Wooden transported with iron chest (iron), 
- chest is placed
- transporter nor used up
- suddenly the chest is "invisible".. but it is there but you can't interact with it

**Comment by 4Magma** [comment]
with 1.11.2 - 2.7.6:
- build a diamond transporter and move some chests (all ok)
- but than i could not mine some cobblestones 
- effects stay on 0:00 and don't disappear 
- if i use now a other tool on a chest, the chest vanished
- if i use a block item (plank, quark hatch) it replace chest or is place like normal

backup restored and reactivated v 2.7.5 is all fine

**Comment by cubex2** [comment]
Should be fixed in 2.7.7 and 2.5.15
