### ISSUE TITLE
[1.10.2] forge-12.18.3.2281 The transporter desyncs from server

### ISSUE THREAD

**Issue by rootwalla** [cubex2/chesttransporter#6]
When a client uses the transporter item, they apparently desynchronise from the server. No changes the client makes (moving a chest) are apparent on the server. In addition the client performing the move, does not lose the debufs.

**Comment by cubex2** [comment]
Are you using the most recent version (2.5.15) that I released earlier today?

**Comment by rootwalla** [comment]
Apologies, when I checked last night, there was only 14. Will test with 15 and report back.

**Comment by rootwalla** [comment]
Tested, 2.5.15 works fine. 
Thanks for the quick reply.
