### ISSUE TITLE
[Suggestion]Add some more configuration in the config file for other stuff

### ISSUE THREAD

**Issue by mcdodge34** [cubex2/chesttransporter#9]
I hate some of the debuffs you choose to force on your mod while carrying any inventory in a chest transporter, I know we can drop them in a backpack, bag of holding or others and that's what I end up doing, I'm ok with a few of them, but some are impossible to manage early on for example if you want to carry a simple chest when you just started your adventures, the recipe is quite easy and that's 100% awesome, but as soon as you have it in your inventory, you can't even jump a single block to move around, this one is driving me insane when I start any modded world, the only solution would be to play in a flat world, is this something you could add a config so we could at least jump 1 block so we could move with theses, even if its slower like with the JABBA dolly.

**Comment by cubex2** [comment]
I've added config options to disable individual debuffs.

**Comment by mcdodge34** [comment]
Thanks a lot, will be very useful once I update it in my pack...
